services:
  # mongo:
  #   image: mongo:6
  #   container_name: blogging-mongo
  #   restart: always
  #   ports:
  #     - "27017:27017"
  #   environment:
  #     MONGO_INITDB_DATABASE: blogging
  #   volumes:
  #     - mongo-data:/data/db

  # mongo-express:
  #   image: mongo-express
  #   container_name: blogging-mongo-express
  #   restart: always
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     ME_CONFIG_MONGODB_SERVER: mongo
  #     ME_CONFIG_MONGODB_PORT: 27017
  #     # ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
  #     # ME_CONFIG_BASICAUTH_USERNAME: admin
  #     # ME_CONFIG_BASICAUTH_PASSWORD: admin
  #   depends_on:
  #     - mongo

  app:
    build: .
    container_name: blogging-api
    restart: always
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    # depends_on:
    #   - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

# volumes:
#   mongo-data: